Allow workway to be used with an existing Worker instance
WebReflection/workway pull request #6
Opened 2019-06-16 17:14 UTC by vishwam

I'd like to use workway with my existing app that's bundled with webpack. The recommended pattern for webpack is to use the [worker-loader](https://github.com/webpack-contrib/worker-loader) module, which does not expose the worker's output path name directly - it returns a function that creates the `Worker` instance instead.

To support this scenario, this PR adds a small change to workway that checks if the input argument is already a `Worker` instance - if it is, it uses the instance directly instead of calling `new Worker()` on it again.

```
> npm-dollar "size"                   
                                      
3465                                  
1408                                  
700                                   
bash: brotli: command not found       
0
```

2019-06-16 19:34 UTC, WebReflection requested changes
I don't understand anything Webpack is doing, but if you are sure this works, then it seems like a minor thing for the library to change, or better, I don't see sensible side-effects.

Please do change the check though, thanks!

2019-06-16 19:34 UTC, WebReflection commented on cjs/index.js
> +    var worker = file instanceof Worker ? file : new Worker(file);
I think what it really works here is `var worker = typeof file === 'string' ? new Worker(file) : file;`, so that any other thing that's not a string will be used right away and eventually throw if needed.

2019-06-16 19:34 UTC, WebReflection commented on esm/index.js
> +    var worker = file instanceof Worker ? file : new Worker(file);
same as before

2019-06-16 19:34 UTC, WebReflection commented on index.js
> +    var worker = file instanceof Worker ? file : new Worker(file);
same as before

2019-06-17 01:53 UTC, vishwam commented on esm/index.js
> +    var worker = file instanceof Worker ? file : new Worker(file);
done

2019-06-17 01:53 UTC, vishwam commented on index.js
> +    var worker = file instanceof Worker ? file : new Worker(file);
done

2019-06-17 01:56 UTC, vishwam commented on cjs/index.js
> +    var worker = file instanceof Worker ? file : new Worker(file);
done! I originally had it that way but changed it to instanceof to be more backwards compatible, just in case people were relying on some weird behavior in the Worker constructor ¯\_(ツ)_/¯ 

I've reverted back to the string check.

2019-06-17 15:21 UTC, vishwam commented
done! I originally had it that way but changed it to instanceof to be more backwards compatible, just in case people were relying on some weird behavior in the Worker constructor ¯\_(ツ)_/¯

I've reverted back to the string check.

2019-06-17 15:38 UTC, merged

2019-06-17 20:07 UTC, WebReflection commented
apologies for the wait: it's live as `0.5.4` 👋

2019-06-18 01:29 UTC, vishwam commented
No problem, thanks for the quick turnaround!